cookie:
  expiry_days: 2
  key: f3d9c8a4e2b1478da2f6b5c4de9a78bc
  name: auth_cookie
credentials:
  usernames:
    boris:
      email: boris.wiessler@gmail.com
      failed_login_attempts: 0
      first_name: Boris
      last_name: Wiessler
      logged_in: true
      password: $2b$12$aQAZto2jsgpTL.KB.gOR0e90URg3LBtYu90cexKE/sun5GEq8fITy
      roles:
      - CEO
